### ISSUE TITLE
Replace GitHub service with webhook or GitHub apps

### ISSUE THREAD

**Issue by jakeg** [lambci/lambci#105]
![image](https://user-images.githubusercontent.com/744792/41406662-e3125faa-6fc4-11e8-9344-0492dd7e4281.png)

**Comment by cjs** [comment]
FWIW this depends on #1 as GitHub Services are webhook based.

**Comment by ngfgrant** [comment]
Github services are going to be officially deprecated tomorrow, 1st October 2018. @mhart does this issue depend on #1 as @cjs suggested?

**Comment by mhart** [comment]
@ngfgrant yes it does. I have it working in a test branch, but it's quite a change (due to the nature of responding to a webhook vs responding to an SNS event).

Events will still be delivered until January 31, 2019 – so existing installations should continue to work until then. But the lack of support for new installations definitely crept up on me.

Hopefully I'll be able to get an update out in the next week or two

**Comment by ngfgrant** [comment]
@mhart - thanks, if you need a hand with anything let me know!

**Comment by monch1962** [comment]
Damn, just hit this problem after putting off installing & playing with LambCI for too long... FWIW I'm happy to test the webhook functionality if you're looking for guinea pigs

**Comment by mhart** [comment]
Ok, have been making progress on this if you'd like to test. You can update your stack, or spin up a new one, using this template:

https://lambci.s3.amazonaws.com/templates/template.yaml

Or you can checkout the code here: https://github.com/lambci/lambci/tree/version-0.10.0

It only creates a webhook at this stage – doing a GitHub App with the new Checks API will be a goal for LambCI v1.0

If you give your GitHub token admin access on repo hooks it will also delete your old SNS hooks when it upgrades – or you can delete them manually.

The webhook will need to be manually added to each repo you want to use it on at `https://github.com/<user>/<project>/settings/hooks/new` – the webhook URL is one of the outputs of the CloudFormation stack and looks something like `https://xb292vl29c.execute-api.us-east-1.amazonaws.com/Prod/lambci/webhook`.

It currently doesn't use a Secret (I'll add this in the next few days) and expects the Content type to be set to "application/json":

<img width="523" alt="screen shot 2018-10-18 at 4 23 36 pm" src="https://user-images.githubusercontent.com/367936/47182295-140bbe80-d2f3-11e8-8c3d-5a29a3a64e09.png">

Also, it's up to you, but to respond to the same events as pre-0.10.0, choose "Let me select individual events." and then select Pushes and Pull Requests:

<img width="606" alt="screen shot 2018-10-18 at 4 33 02 pm" src="https://user-images.githubusercontent.com/367936/47182582-c6dc1c80-d2f3-11e8-9d7f-301c45dc19d2.png">

Let me know if you have any questions or comments on how it's going so far!

**Comment by mhart** [comment]
(I'll update this thread once I've pushed v0.10 out for real – I basically just need to update the README, quite a bit, as well as add support for the webhook Secret)

**Comment by mhart** [comment]
Have just pushed support in that branch for webhook secrets – and updated the template at https://lambci.s3.amazonaws.com/templates/template.yaml as well.

So you now need to have a webhook secret, and you can set that in the Cloudformation Stack parameters – or manually add to the global config table as `secretEnv.GITHUB_SECRET` (as an aside, I'll be adding support for AWS SSM to store secrets in v1.0 – for now they're still stored in DynamoDB)

Now to document a lot of things!

**Comment by jakeg** [comment]
@mhart have installed from these instructions and the new branch yesterday. All worked perfectly. Thank you :)

**Comment by riderx** [comment]
💪thanks a lot !

**Comment by riderx** [comment]
i did the install of version-0.10.0 but i still get ENOSPC error when npm install dependencies do you know why ? my lambda has 3GB of memorie on aws and my npm folder is 560 mb on disk so the space should be ok .

**Comment by mhart** [comment]
@riderx Lambda only has 500MB of disk space – time to trim some of those npm dependencies!

**Comment by mhart** [comment]
Finally done – just released 0.10.0 with webhooks support... next up, Checks API!
